# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import plotly.graph_objects as go

#As linhas abaixo são responsaveis por puxar o arquivo csv  e ler o mesmo 
base = pd.read_csv('https://raw.githubusercontent.com/EdPPF/APC-Parte01/main/co2-emissions-by-fuel-line_1.csv')
base_array = base.values

#A função a baixo é responsavel por trasnformar os elementos da base de dados em listas. facilitando a manipulação 
paises = []
anos = []
oleo = []
queimada = []
cement = []
carvao = []
gas = []
for elemento in base_array:
    paises.append(elemento[0])
    anos.append(elemento[2])
    oleo.append(elemento[3])
    queimada.append(elemento[4])
    cement.append(elemento[5])
    carvao.append(elemento[6])
    gas.append(elemento[7])

#A função a baixo é pra apagar os dados da base de dados que não iremos ultilizar 

listas = [paises, anos, oleo, queimada, cement, carvao, gas]
for lista in listas:
    del lista[:3210]
    del lista[29:5130]
    del lista[58:3539]
    del lista[87:6808]
    del lista[116:3597]
    del lista[145:19016]
    del lista[174:11485]
    del lista[203:8004]
    del lista[232:]

# Criando outra lista de listas para trabalhar com elas individualmente:
listas_sub = [gas, carvao, cement, queimada, oleo]

# "Values" armazenará os valores das médias que compõem o gráfico
Values = []
# Calculando os somatórios dos valores em cada lista e armazenando as médias em Values: 
for lista in listas_sub:
    soma = 0
    for nota in lista:
        soma += nota
    Values.append(int(soma)/232)

labels = ['Gasolina' , 'Carvão',  'Cimento' ,'Queimadas', 'Óleo']
#Criando o Grafico 
fig = go.Figure([go.Pie(labels=labels, values=Values,)])
#Color = função criada para dar cor a cada termo do grafico 
colors = ['gold', 'Crimson', 'LightSlateGray', 'Black', 'Chartreuse']
#line=dict( color='#4169E1',width=2 ) = Grifar as linhas de azul royal

fig.update_traces(textfont_size=15, marker=dict(colors=colors, line=dict( color='#4169E1',width=2 ) ))
#title_text= da um titulo ao gráfico, <br> <sup> apos isso é dado um subtitulo ao grafico 
fig.update_layout(title_text='EMISSÕES DE CO2 NOS SETORES DE COMBUSTÍVEIS <br> <sup> Valores referentes a Ásia, América,Europa,Brasil,China, EUA e Alemanha', template = 'plotly_dark')
fig.show()